name: Run Unit Tests

on:
  workflow_dispatch:
    inputs:
      test_file:
        description: 'Select which test file to run'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - GuessingGameTest
          - ScoreboardTest

jobs:
  run_tests:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests with Maven
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ inputs.test_file }}" != "all" ]; then
            mvn -B package -Dtest=${{ inputs.test_file }} --file pom.xml
          else
            mvn -B package --file pom.xml
          fi

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
